; Model 3 of Zwart TC et al., Clin Pharmacokinet 2021;60:191-203 (doi 10.1007/s40262-020-00925-8), Electronic Supplementary Material 5.
; Copied verbatim from the supplement (open-access article) for the NONMEM cross-check; units in the comments are the supplement's own.
; NOT yet run in this project. See docs/HANDOFF_EVEROLIMUS_M3.md for what has to be checked first.

; (section title in the supplement: NONMEM code for Model 3)

$SUBROUTINE ADVAN6 TOL=9

$MODEL
COMP=(DOSE)
COMP=(LIVER)
COMP=(CENTRAL)
COMP=(PERIPH)
COMP=(TRAN)
COMP=(TRAN)
COMP=(TRAN)
COMP=(TRAN)
COMP=(AUCPL);9
COMP=(AUCBL);10

$PK
VL=1.55 ; BASED ON MEAN CALCULATED LIVER VOLUME

; --- FLAGS
FLA1=0
FLA2=0
FLA3=0
IF (OCC.EQ.1) FLA1=1
IF (OCC.GE.2) FLA2=1
IF (STUDY.EQ.2) FLA3=1

; --- ABSORPTION
IOVMAT=(FLA1*ETA(3))+(FLA2*ETA(4))
F1=1
MAT=THETA(1)*EXP(IOVMAT) ; CALCULATION OF MEAN ABSORPTION TIME
KA=5/MAT ; CALCULATION OF MEAN ABSORPTION TIME

; --- FLAG STUDY 4 (HIGH DOSE PREDNISOLONE)
FLA4=0
IF (STUDY.EQ.4) FLA4=1

; --- VIRTUAL AUC COMPARTMENT RESET
FLA9 = 1
IF (EVID.EQ.1) FLA9 = 0 ; ONLY INTEGRATE OVER ACTUAL DOSING INTERVAL
FLA10 = 1
IF (EVID.EQ.1) FLA10 = 0 ; ONLY INTEGRATE OVER ACTUAL DOSING INTERVAL

; --- DISTRIBUTION AND CLEARANCE OF EVEROLIMUS
FU=0.27*EXP(ETA(5))
QH=90 ; HEPATIC BLOOD FLOW L/H
QHP=QH*(1-HT) ; CALCULATE HEPATIC PLASMA FLOW
TVCLINT=THETA(2)*(THETA(6)**FLA4) ; TYPICAL VALUE INTRINSIC CLEARANCE
CLINT=TVCLINT*EXP(ETA(1)) ; INTRINSIC CLEARANCE
TVV3=THETA(3) ; TYPICAL VALUE V3
V3=THETA(3)*EXP(ETA(2)) ; V3
Q=THETA(4) ; INTERCOMPARTMENTAL CLEARANCE
TVV4=THETA(5) ; TYPICAL VALUE V4
V4=TVV4 ; V4
S3=V3           ; SCALING FOR OBSERVATIONS IN COMPARTMENT 3

; --- MASS TRANSPORT
EH=(CLINT*FU)/(QHP+(CLINT*FU)) ; HEPATIC EXTRACTION
CLH=EH*QHP ; HEPATIC CLEARANCE
K15=KA
K56=K15
K67=K56
K78=K67
K82=K78
K20=CLH/VL
K23=(QHP*(1-EH))/VL
K32=QHP/V3
K34=Q/V3
K43=Q/V4

$DES
DADT(1)=-K15*A(1)
DADT(2)=-K20*A(2)-K23*A(2)+K82*A(8)+K32*A(3)
DADT(3)=-K32*A(3)-K34*A(3)+K23*A(2)+K43*A(4)
DADT(4)=-K43*A(4)+K34*A(3)
DADT(5)=-K56*A(5)+K15*A(1)
DADT(6)=-K67*A(6)+K56*A(5)
DADT(7)=-K78*A(7)+K67*A(6)
DADT(8)=-K82*A(8)+K78*A(7)
CPLI=A(3)/V3 ; PLASMA CONCENTRATION IN V3
BMAXI=0.96425 ; DERIVED MG/L
KDI=0.09195 ; DERIVED MG/L
KNSI=0.15336 ; DERIVED MG/L
CRBI=((BMAXI*CPLI)/(KDI+CPLI))+(KNSI*CPLI) ; SPECIFIC AND NON-SPECIFIC BINDING
CBLI=(CRBI*HT)+(CPLI*(1-HT)) ; CALCULATES WHOLE BLOOD CONCENTRATIONS
DADT(9)=CPLI * FLA9 ; INTEGRATES PLASMA CONCENTRATION V3 OVER TIME
DADT(10)=CBLI * FLA10 ; INTEGRATES WHOLE BLOOD CONCENTRATION V3 OVER TIME

$ERROR
CPL=F ; CALCULATES PLASMA PK PARAMETERS IN RESULTS
BMAX=0.96425 ; DERIVED MG/L
KD=0.09195 ; DERIVED MG/L
KNS=0.15336 ; DERIVED MG/L
CRB=((BMAX*CPL)/(KD+CPL))+(KNS*CPL) ; SPECIFIC AND NON-SPECIFIC BINDING
CBL=(CRB*HT)+(CPL*(1-HT)) ; CALCULATES WHOLE BLOOD CONCENTRATIONS
IPRED=LOG(CBL+1E-16) ; LOG TRANSFORMED WHOLE BLOOD CONCENTRATIONS
Y=IPRED+ERR(1) ; RESIDUAL ERROR MODEL
AUCPL=A(9) ; AUC PLASMA UG/L*H
AUCBL=A(10) ; AUC BLOOD UG/L*H

$THETA
0.549 FIX ; MEAN ABSORPTION TIME THROUGH 4 TRANSIT COMPARTMENTS (H)
322 FIX ; INTRINSIC CLEARANCE (L/H)
266 FIX ; V3 CENTRAL PLASMA COMPARTMENT VOLUME (L)
79.5 FIX ; INTERCOMPARTMENTAL CLEARANCE (L/H)
519 FIX ; V4 PERIPHERAL PLASMA COMPARTMENT VOLUME (L)
1.44 FIX ; HIGH DOSE PRED ON CLINT
$OMEGA
0.118 ; IIV CLINT
0.401 ; IIV V3
$OMEGA BLOCK(1) 0 FIX ; IOV MAT
$OMEGA BLOCK(1) SAME ; IOV MAT
$OMEGA 0.0009 FIX ; IIV FU - KOVARIK ET AL

$SIGMA
0.0957 ; PROP ERR

$EST METHOD=1 INTER MAXEVAL=0 NOABORT NSIG=3 SIGL=9 PRINT=1 POSTHOC
