; Structure: the control stream of run 57 (26 April 2023), extracted VERBATIM from mmfrun57.lst (authoritative for compartments and scaling),
; EXCEPT that the $THETA/$OMEGA/$SIGMA blocks hold the ARTICLE's values (Heida 2024, Table 2 / ESM stream), by owner decision.
; Original initial values of run 57 were THETA 10 30 2000 30 3 -1; OMEGA 0.1 1 0 0.1 0 / IOV 0.1; SIGMA 0.1.
;; 1. Based on: mmfrun56
;; 2. Description: Nieuwe start ADVAN5 SS=0 TRANSIT ALB
;; x1. Author: user
$PROBLEM    RUN05
$INPUT      ID TIME DOTI AMT EVID CMT MDV DV LNDV II SS OCC WT HT SEX
            ALB TACR CICL EVER AGE BSA DBSA
$DATA      mmf18april2023v3.csv ignore=@ IGNORE(CMT.EQ.4)
 ; DATASET MET AMT=1 IN CMT=4 OP T=DOSETIMECURVE
$SUBROUTINE ADVAN5
$MODEL      COMP=(DOSE) COMP=(CENTRAL) COMP=(PERIPHERAL) COMP=(TRAN)
$PK  
; Time after dose needed for creating VPCs
IF (AMT.GT.0) THEN
TDOS=TIME
TAD=0.0
ENDIF
IF (AMT.EQ.0) TAD=TIME-TDOS

IF (OCC.EQ.1) IOV=ETA(6)
IF (OCC.EQ.2) IOV=ETA(7)
IF (OCC.EQ.3) IOV=ETA(8)
IF (OCC.EQ.4) IOV=ETA(9)
IF (OCC.EQ.5) IOV=ETA(10)
IF (OCC.EQ.6) IOV=ETA(11)
IF (OCC.EQ.7) IOV=ETA(12)
IF (OCC.EQ.8) IOV=ETA(13)
IF (OCC.EQ.9) IOV=ETA(14)
IF (OCC.EQ.10) IOV=ETA(15)

ALLOCL=(WT/70)**0.75
ALLOV=(WT/70)
ALLOK=(WT/70)**(-0.25)

COVALB=(ALB/34)**THETA(6)
CL=THETA(1)*ALLOCL*COVALB*EXP(ETA(1))
V2=THETA(2)*ALLOV*EXP(ETA(2))
V3=THETA(3)*ALLOV*EXP(ETA(3))
Q=THETA(4)*ALLOCL*EXP(ETA(4))
KTR=THETA(5)*ALLOK*EXP(ETA(5))

F1=1*EXP(IOV)

S2=V2

K14=KTR
K42=KTR
K23=Q/V2
K32=Q/V3
K20=CL/V2


$ERROR  
IPRED=F
Y=IPRED+IPRED*ERR(1)

$THETA  16.0   ; CL
 24.9   ; V2 (central)
 1590   ; V3 (peripheral)
 36.2   ; Q
 1.48   ; KTR
 -2.49  ; ALB~CL
$OMEGA  0.139  ;   1 IIV CL
 2.42  ;   2 IIV V2
 0  FIX  ;   3 IIV V3
 0.337  ;    4 IIV Q
 0  FIX  ;   5 IIV KTR
$OMEGA  BLOCK(1)
 0.19  ;      OCC 1
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$OMEGA  BLOCK(1) SAME
$SIGMA  0.223  ;   PROP ERR
$ESTIMATION METHOD=1 NSIG=2 INTERACTION MAXEVAL=2000 NOHABORT
$COVARIANCE PRINT=E MATRIX=S UNCONDITIONAL
$TABLE      ID TIME TAD AMT EVID CMT MDV DV II SS OCC WT HT SEX ALB
            TACR CICL EVER AGE CL V2 V3 Q KTR PRED IPRED CWRES ETA(1)
            ETA(2) ETA(3) ETA(4) ETA(5) NOAPPEND NOPRINT ONEHEADER
            FILE=SDTABmmf57.tab
